services:
  app:
    image: ghcr.io/tunaground/openchamchijs:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./GeoLite2-Country.mmdb:/app/lib/GeoLite2-Country.mmdb:ro
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "2"
    restart: unless-stopped
